USE [master]
GO

/****** Object:  Database [gl-test]    Script Date: 22/05/2024 1:14:04 p. m. ******/
DROP DATABASE [gl-test]
GO

/****** Object:  Database [gl-test]    Script Date: 22/05/2024 1:14:04 p. m. ******/
CREATE DATABASE [gl-test]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'gl-test', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\gl-test.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'gl-test_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\gl-test_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [gl-test].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [gl-test] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [gl-test] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [gl-test] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [gl-test] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [gl-test] SET ARITHABORT OFF 
GO

ALTER DATABASE [gl-test] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [gl-test] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [gl-test] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [gl-test] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [gl-test] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [gl-test] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [gl-test] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [gl-test] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [gl-test] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [gl-test] SET  DISABLE_BROKER 
GO

ALTER DATABASE [gl-test] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [gl-test] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [gl-test] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [gl-test] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [gl-test] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [gl-test] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [gl-test] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [gl-test] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [gl-test] SET  MULTI_USER 
GO

ALTER DATABASE [gl-test] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [gl-test] SET DB_CHAINING OFF 
GO

ALTER DATABASE [gl-test] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [gl-test] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [gl-test] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [gl-test] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [gl-test] SET QUERY_STORE = ON
GO

ALTER DATABASE [gl-test] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [gl-test] SET  READ_WRITE 
GO


